-- Create tables for Customer Service Agent (see docs/database.md)
-- Run against your Postgres DB, e.g. psql $DATABASE_URL -f app/init_db/create_tables.sql

-- CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE customers (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone       VARCHAR(32),
    email       VARCHAR(255),
    name        VARCHAR(255),
    plan        VARCHAR(64),
    status      VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_customers_phone ON customers (phone) WHERE phone IS NOT NULL;

-- Bookable resources: clinicians, rooms, equipment (shared clinic calendar per resource).
CREATE TABLE provider_names (
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_provider_names_name ON provider_names (name);
INSERT INTO provider_names (name) VALUES ('Doctor'), ('Nurse'), ('Room'), ('Equipment');

CREATE TABLE providers (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kind       INTEGER NOT NULL REFERENCES provider_names (id),
    name       VARCHAR(255) NOT NULL,
    active     BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_providers_kind ON providers (kind) WHERE active = true;


-- 30-minute slot starts (clinic-local wall clock). Lunch 13:00–14:00 omitted from templates.
CREATE TABLE slot_templates (
    id         SMALLINT PRIMARY KEY,
    start_time TIME NOT NULL UNIQUE
);

INSERT INTO slot_templates (id, start_time) VALUES
    (1, '09:00'), (2, '09:30'), (3, '10:00'), (4, '10:30'), (5, '11:00'), (6, '11:30'),
    (7, '14:00'), (8, '14:30'), (9, '15:00'), (10, '15:30'), (11, '16:00'), (12, '16:30')
ON CONFLICT (id) DO NOTHING;


CREATE TABLE general_statuses (
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_general_statuses_name ON general_statuses (name);
INSERT INTO general_statuses (name) VALUES ('pending'), ('scheduled'), ('completed'), ('cancelled');

CREATE TABLE callback_requests (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id   UUID REFERENCES customers (id) ON DELETE SET NULL,
    phone         VARCHAR(32) NOT NULL,
    requested_for VARCHAR(128),
    status        INTEGER NOT NULL REFERENCES general_statuses (id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE appointments (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id  UUID REFERENCES customers (id) ON DELETE SET NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    subject      VARCHAR(255) NOT NULL,
    status       INTEGER NOT NULL REFERENCES general_statuses (id),
    notes        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_appointments_scheduled_at ON appointments (scheduled_at);
CREATE INDEX idx_appointments_customer_id ON appointments (customer_id);

-- One row per resource reserved for an appointment (created on confirm). No pre-generated “available” rows.
-- UNIQUE (provider_id, booking_date, slot_template_id) prevents double-booking per resource per slot.
CREATE TABLE appointment_resource_bookings (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    appointment_id   UUID NOT NULL REFERENCES appointments (id) ON DELETE CASCADE,
    provider_id      UUID NOT NULL REFERENCES providers (id) ON DELETE RESTRICT,
    booking_date     DATE NOT NULL,
    slot_template_id SMALLINT NOT NULL REFERENCES slot_templates (id) ON DELETE RESTRICT,
    status           INTEGER NOT NULL REFERENCES general_statuses (id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider_id, booking_date, slot_template_id)
);
CREATE INDEX idx_appointment_resource_bookings_lookup
    ON appointment_resource_bookings (provider_id, booking_date);
CREATE INDEX idx_appointment_resource_bookings_appointment
    ON appointment_resource_bookings (appointment_id);


-- ============================================================================
-- RAG / Clinical Tables
-- See docs/RAG.md for full architecture.
-- RXNCONSO is stored entirely in Milvus (Zilliz) — NOT in PostgreSQL.
-- The following tables are PostgreSQL-only (no vectors, pure relational).
-- ============================================================================

-- Clinical note metadata (vectors stored in Milvus: clinical_note_vectors)
CREATE TABLE clinical_note_embeddings (
    id          SERIAL PRIMARY KEY,
    note_hash   VARCHAR(64) UNIQUE,
    icd10_codes TEXT[],
    cpt_codes   TEXT[],
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Clinic drug inventory (product-level NDC for billing / dispensing linkage)
CREATE TABLE inventory (
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    drug_name  VARCHAR(512) NOT NULL,
    ndc        VARCHAR(32)
);
CREATE INDEX idx_inventory_ndc ON inventory (ndc) WHERE ndc IS NOT NULL;

-- UMLS concept cache (vectors stored in Milvus: umls_vectors)
CREATE TABLE umls_concepts (
    cui                 VARCHAR(8) PRIMARY KEY,
    concept_name        TEXT,
    semantic_type       VARCHAR(10),
    source_vocabularies TEXT[]
);

-- RXNREL: concept relationships (brand↔generic, ingredient, dose form)
CREATE TABLE rxnorm_relationships (
    id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rxcui1    VARCHAR(8),
    rxaui1    VARCHAR(8),
    stype1    VARCHAR(10),
    rel       VARCHAR(10),
    rxcui2    VARCHAR(8),
    rxaui2    VARCHAR(8),
    stype2    VARCHAR(10),
    rela      VARCHAR(50),
    rui       VARCHAR(12),
    srui      VARCHAR(12),
    sab       VARCHAR(20),
    sl        VARCHAR(50),
    rg        VARCHAR(12),
    dir       VARCHAR(1),
    suppress  VARCHAR(1),
    cvf       VARCHAR(10)
);

-- RXNSAT: attributes, NDC codes, RxNORM-specific properties
CREATE TABLE rxnorm_attributes (
    id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rxcui    VARCHAR(8),
    lui      VARCHAR(8),
    sui      VARCHAR(8),
    rxaui    VARCHAR(8),
    stype    VARCHAR(10),
    code     VARCHAR(20),
    atui     VARCHAR(12),
    satui    VARCHAR(12),
    atn      VARCHAR(50),
    sab      VARCHAR(20),
    atv      TEXT,
    suppress VARCHAR(1),
    cvf      VARCHAR(10)
);

-- RXNSTY: semantic type classification
CREATE TABLE rxnorm_semantic_types (
    id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rxcui VARCHAR(8),
    tui   VARCHAR(10),
    stn   VARCHAR(30),
    sty   VARCHAR(100),
    atui  VARCHAR(12),
    cvf   VARCHAR(10)
);

-- RXNDOC: abbreviation / reference lookup
CREATE TABLE rxnorm_documentation (
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key_val   VARCHAR(100),
    value_val TEXT,
    type_val  VARCHAR(10),
    expl      TEXT
);

-- Drug interaction cache
CREATE TABLE drug_interactions (
    id           SERIAL PRIMARY KEY,
    drug1_rxcui  VARCHAR(8),
    drug2_rxcui  VARCHAR(8),
    severity     VARCHAR(20),
    description  TEXT,
    mechanism    TEXT
);

-- RxNorm relational indexes
CREATE INDEX idx_rxnorm_relationships_rxcui1 ON rxnorm_relationships (rxcui1);
CREATE INDEX idx_rxnorm_relationships_rxcui2 ON rxnorm_relationships (rxcui2);
CREATE INDEX idx_rxnorm_relationships_rel    ON rxnorm_relationships (rel);
CREATE INDEX idx_rxnorm_relationships_rela   ON rxnorm_relationships (rela);
CREATE INDEX idx_rxnorm_attributes_rxcui     ON rxnorm_attributes (rxcui);
CREATE INDEX idx_rxnorm_attributes_atn       ON rxnorm_attributes (atn);
CREATE INDEX idx_rxnorm_semantic_types_rxcui ON rxnorm_semantic_types (rxcui);
