-- Create tables for Customer Service Agent (see docs/database.md)
-- Run against your Postgres DB, e.g. psql $DATABASE_URL -f app/init_db/create_tables.sql

-- CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE customers (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone       VARCHAR(32),
    email       VARCHAR(255),
    name        VARCHAR(255),
    plan        VARCHAR(64),
    status      VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_customers_phone ON customers (phone) WHERE phone IS NOT NULL;

-- Bookable resources: clinicians, rooms, equipment (shared clinic calendar per resource).
CREATE TABLE provider_names (
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_provider_names_name ON provider_names (name);
INSERT INTO provider_names (name) VALUES ('Doctor'), ('Nurse'), ('Room'), ('Equipment');

CREATE TABLE providers (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kind       INTEGER NOT NULL REFERENCES provider_names (id),
    name       VARCHAR(255) NOT NULL,
    active     BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_providers_kind ON providers (kind) WHERE active = true;


-- 30-minute slot starts (clinic-local wall clock). Lunch 13:00–14:00 omitted from templates.
CREATE TABLE slot_templates (
    id         SMALLINT PRIMARY KEY,
    start_time TIME NOT NULL UNIQUE
);

INSERT INTO slot_templates (id, start_time) VALUES
    (1, '09:00'), (2, '09:30'), (3, '10:00'), (4, '10:30'), (5, '11:00'), (6, '11:30'),
    (7, '14:00'), (8, '14:30'), (9, '15:00'), (10, '15:30'), (11, '16:00'), (12, '16:30')
ON CONFLICT (id) DO NOTHING;


CREATE TABLE general_statuses (
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_general_statuses_name ON general_statuses (name);
INSERT INTO general_statuses (name) VALUES ('pending'), ('scheduled'), ('completed'), ('cancelled');

CREATE TABLE callback_requests (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id   UUID REFERENCES customers (id) ON DELETE SET NULL,
    phone         VARCHAR(32) NOT NULL,
    requested_for VARCHAR(128),
    status        INTEGER NOT NULL REFERENCES general_statuses (id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE appointments (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id  UUID REFERENCES customers (id) ON DELETE SET NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    subject      VARCHAR(255) NOT NULL,
    status       INTEGER NOT NULL REFERENCES general_statuses (id),
    notes        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_appointments_scheduled_at ON appointments (scheduled_at);
CREATE INDEX idx_appointments_customer_id ON appointments (customer_id);

-- One row per resource reserved for an appointment (created on confirm). No pre-generated “available” rows.
-- UNIQUE (provider_id, booking_date, slot_template_id) prevents double-booking per resource per slot.
CREATE TABLE appointment_resource_bookings (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    appointment_id   UUID NOT NULL REFERENCES appointments (id) ON DELETE CASCADE,
    provider_id      UUID NOT NULL REFERENCES providers (id) ON DELETE RESTRICT,
    booking_date     DATE NOT NULL,
    slot_template_id SMALLINT NOT NULL REFERENCES slot_templates (id) ON DELETE RESTRICT,
    status           INTEGER NOT NULL REFERENCES general_statuses (id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider_id, booking_date, slot_template_id)
);
CREATE INDEX idx_appointment_resource_bookings_lookup
    ON appointment_resource_bookings (provider_id, booking_date);
CREATE INDEX idx_appointment_resource_bookings_appointment
    ON appointment_resource_bookings (appointment_id);
